development:
  type: http
  url: http://neo4j:neo4j4@localhost:7474
  # username: neo4j
  # password: neo4j4

test:
  type: http
  url: http://localhost:7575

production:
  type: http
  url: http://neo4j:password@localhost:7000
